gen EduLevel_Weighted=(Eduscore*0.125)
gen Skill_Weighted=(Skillscore*0.125)
gen BMI_Weighted=(BMIScore*0.05)
gen ST_ill_Weighted=(STillscore*0.05)
gen LT_ill_Weighted=(LTillscore*0.05)
gen PhysicalAct_Weighted=(Activity_score*0.05)
gen Alcohol_Weighted=(Alchol_score*0.025)
gen Tobacco_Weighted= (Tabacoo_score*0.025)
gen NEET_Weighted=(NEET*0.10)
gen Unemployment_Weighted=(Unemployed*0.10)
gen LF_Weighted= (Labourforce*0.05)
gen Voter_Weighted= (VoterReg_score*0.02)
gen LastVoted_Weighted= (lastVoted_score*0.02)
gen PoliticalAction_Weighted= (PoliticalActions_score*0.02)
gen YouthProg_Weighted= (YP_score*0.03)
gen NGO_Weighted= (NGO_score*0.03)
gen SocialInclusion= (socialInclusion_score*0.065)
gen DisableInclusion=(differnltyable_score*0.065)
gen HealthIndex=(BMI_Weighted+ST_ill_Weighted+LT_ill_Weighted+PhysicalAct_Weighted+Alcohol_Weighted+Tobacco_Weighted )/0.25
gen EmplymentIndex= (NEET_Weighted+ Unemployment_Weighted+ LF_Weighted)/0.25
gen EducationIndex=(EduLevel_Weighted+ Skill_Weighted)/0.25
gen PoliticalIndex= (Voter_Weighted+ LastVoted_Weighted+ PoliticalAction_Weighted)/0.06
gen CivicIndex= (YouthProg_Weighted+ NGO_Weighted)/0.06
gen SocialIndex= (SocialInclusion+ DisableInclusion)/0.13
gen YDI= EducationIndex+HealthIndex+EmplymentIndex+PoliticalIndex+CivicIndex+SocialIndex
